name: my-first-workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: first-step
              run: |
                    echo "hello there!"
                    echo "I am running"
            - name: printing logs
              run: echo $"{{ toJSON(github)}}"
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: download code
              uses: actions/checkout@v4
            - name: downlaod nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 16
           